#ifndef ENCRYPTION_H
#define ENCRYPTION_H

#include "includes.h"
#include <sodium.h>

// Chunk size for file reading/writing (e.g., 4KB)
#define CHUNK_SIZE 1048576

class encryption {
public:

    encryption();

    /**
     * checks whether the user is new or an old user by checking if the foo file is exists and is empty
     * this is done to not double encrypt the file
     * 
     * @returns true if the user is new, false if not
     */
    bool firstTimeUser();

    /**
     * wrapper function to encrypt the file
     */
    void encrypt();

    /**
     * wrapper function to decrypt the file
     */
    void decrypt();

    /**
     * generates the hash and saves it to the file defined in userPass
     * 
     * @param hashPass hash master password
     */
    void genHashtoFile(std::string hashpass); //TODO: make a new method in this class that performs the operations here instead of TUIFrontEnd class 

    std::string fetchHash();

    /**
     * compares the password and hash using crypto_pwhash_str_verify()
     * 
     * @param password entered by user
     * @param storedHash hash generated by argon2id 
     * 
     * @return true if passwords match, false if they are corrupted
     */
    bool isPasswordCorrect(const std::string& password, const std::string& storedHash);


private:
    /**
     * it is the const char* version of path since libsodium library is written in C
     */
    const char* pathS = path.c_str();
    /**
     * it is the const char* version of tempFile since libsodium library is written in C
     */
    const char* tempFileS = tempfile.c_str();

    /**
     * a file to store the key
     */
    std::string passFile = "untitled.txt";

    /**
     * fetches the hash from file defined in passFile string
     * 
     * @return hash string
     */
    std::string userPass;

    std::vector<std::string> rawStr;
    std::vector<std::string> convertToRawString(std::vector<siteObj> &sites);
    void convertToVectObj();
    
    /**
     * creates the master password from the user
     * if both the passwords match generate the hash using argon2id
     */
    void createPassword();
    std::vector<uint8_t> serializeVector(const std::vector<std::string>& vec);
    std::vector<std::string> deserializeVector(const std::vector<uint8_t>& buffer);
    
    /**
     * verifies the user by making the user enter the master password
     * 
     * @return true if match, false otherwise
     */
    bool verifyUser();

    /**
     * generates hash using crypto_pwhash_str()
     * 
     * @param password password from the user when enter for the first time
     * @return a hash
     */
    std::string hashPassword(const std::string& password);

    /**
     * decrypts the file into the RAM where it gets stored to siteData vector which is a global variable
     * 
     * @param sourcePath path to the encrypted file
     * @param outputVector vector to copy data to
     * @param password the hash generated from master password is the key
     * 
     * @return whether a file was successfully decrypted and loaded into RAM using a vector
     */
    bool decryptContentToRAM(const filesystem::path& sourcePath, std::vector<std::string>& outVector, const std::string& password);
    
    /**
     * encrypts to the file from siteData vector which is a global variable
     * 
     * @param targetPath path to the encrypted file
     * @param dataVector vector to save data to file
     * @param password the hash generated from master password is the key
     * 
     * @return a boolean where a file was successfully encrypted or not
     */
    bool encryptVectorToFile(const filesystem::path &targetPath, const std::vector<std::string>& dataVector, const std::string& password);
};

#endif