#ifndef ENCRYPTION_H
#define ENCRYPTION_H

#include "includes.h"
#include <sodium.h>

// Chunk size for file reading/writing (4KB)
#define CHUNK_SIZE 4096

/**
 * this class handles the encrypting and decrypting the database and master password hashing
 */
class encryption {
public:

    encryption() = default;

    /**
     * checks whether the user is new or an old user by checking if the database file exists or is empty
     * this is done to not double encrypt the file when the program closes
     * 
     * @returns true if the user is new, false if not
     */
    bool firstTimeUser();

    /**
     * wrapper function to encrypt the file
     */
    void encrypt();

    /**
     * wrapper function to decrypt the file
     */
    void decrypt();

    /**
     * generates the hash and returns the hash
     * 
     * @param hashPass hashed master password
     */
    void genHashtoFile(std::string hashPass); 

    /**
     * fetches the hash from the keylog file
     * 
     * @return hash from keylog file
     */
    std::string fetchHash();

    /**
     * remove trailing chars like whitespace and LF, CRLF line endings. 
     * it is mostly used in clearing out junk before verification of hash  
     */    
    static void removeTrailingChars(std::string &text);
    
    /**
     * verifies the password and hash using crypto_pwhash_str_verify()
     * 
     * @param password entered by user
     * @param storedHash hash generated by argon2id from the keylog file
     * 
     * @return true if passwords match, false if they are corrupted or incorrect
     */
    bool isPasswordCorrect(const std::string& password, const std::string& storedHash);


private:

    /**
     * these are limits that encryption and decryption function can use
     * they are chosen as a compromise between latency and security
     * this is in bytes multiplied by 1024 as to make it easy to change 
     */
    size_t customMemLimit = 128 * 1024 * 1024; //128MB    

    /**
     * these are limits that encryption and decryption function can use
     * they are chosen as a compromise between latency and security 
     */
    unsigned long long customOpsLimit = 3; //3 iterations

    /**
     * it is the const char* version of path since libsodium library is written in C
     */
    const char* pathS = path.c_str();
    
    /**
     * file name for the master password
     */
    const std::string passFileName = "keylog";

    /**
    * a file to store the Argon2id key in different OS paths
    */
    #if defined(_WIN32)
        /**
         * Windows key store path, search in local directory of a user, C: drive for fallback
        */ 
        const std::string passFile = ((localAppDir && localAppDir[0] != '\0') ? std::filesystem::path(localAppDir) / "STPM" / passFileName
        : std::filesystem::path("C:\\STPM\\keylog")).string();
    #elif defined(__APPLE__)
        /**
         * macOS key store path, search in app support, current directory for fallback
        */
        const std::string passFile = ((homeConfig && homeConfig[0] != '\0')
        ? std::filesystem::path(homeConfig) / "Library" / "Application Support" / "STPM" / passFileName
        : std::filesystem::path(".") / "STPM" / passFileName).string();
    #elif defined(__linux__)
        /**
         * Linux key store path, search in XDG_CONFIG_HOME and HOME first, current directory for fallback
        */    
        const std::string passFile = 
        ((xdgEnv && xdgEnv[0] == '/')
            ? std::filesystem::path(xdgEnv) / "STPM" / passFileName
            : (homeEnv && homeEnv[0] != '\0')
                ? std::filesystem::path(homeEnv) / ".config" / "STPM" / passFileName
                : std::filesystem::path(".") / "STPM" / passFileName).string();
    #else
        #error "Unsupported platform! you tryna compile in BSD or mobile or embedded?"
    #endif

    /**
     * contains data in raw strings, this is used later in making a object vector, making it easy to work on.
     */
    std::vector<std::string> rawStr;
    
    /**
     * convert object vector to raw strings 
     * 
     * @param sites a vector object containing siteObj objects 
     */
    std::vector<std::string> convertToRawString(std::vector<siteObj> &sites);

    /**
     * convert raw strings to object vector
     */
    void convertToVectObj();
    
    /**
     * creates the master password from the user
     * if both the passwords match generate the hash using argon2id
     */
    void createPassword();

    /**
     * converts a string Vector to utint8_t Vector
     */
    std::vector<uint8_t> serializeVector(const std::vector<std::string>& vec);

    /**
     * converts a utint8_t Vector to std::string Vector
     */    
    std::vector<std::string> deserializeVector(const std::vector<uint8_t>& buffer);
    
    /**
     * verifies the user by making the user enter the master password
     * 
     * @return true if match, false otherwise
     */
    bool verifyUser();

    /**
     * generates hash using crypto_pwhash_str()
     * 
     * @param password password from the user when enter for the first time
     * @return a hash
     */
    std::string hashPassword(const std::string& password);

    /**
     * decrypts the file into the RAM where it gets stored to siteData vector which is a global variable
     * 
     * @param sourcePath path to the encrypted file
     * @param outputVector vector to copy data to
     * @param password the hash generated from master password is the key
     * 
     * @return whether a file was successfully decrypted and loaded into RAM using a vector
     */
    bool decryptContentToRAM(const filesystem::path& sourcePath, std::vector<std::string>& outVector, const std::string& password);
    
    /**
     * encrypts to the file from siteData vector which is a global variable
     * 
     * @param targetPath path to the encrypted file
     * @param dataVector vector to save data to file
     * @param password the hash generated from master password is the key
     * 
     * @return a boolean where a file was successfully encrypted or not
     */
    bool encryptVectorToFile(const filesystem::path &targetPath, const std::vector<std::string>& dataVector, const std::string& password);
};

#endif